name: "File Integrity Checker"
description: "Checks the integrity of modified files using SHA256."
inputs:
  path:
    description: "Path to the files to check."
    required: true
    default: "."
outputs:
  checksums:
    description: "The SHA256 checksum of the modified files."
runs:
  using: "composite"
  steps:
    - name: Run Python Script
      run: python3 shasum_action.py  # Replace `main.py` with your script's name
      shell: bash
